<?php 
$smile = [
':)'         =>  '<img src="img/1.gif" alt="happy">',
':('         =>  '<img src="img/2.gif" alt="sad">',
';)'         =>  '<img src="img/3.gif" alt="winking">',
':D'         =>  '<img src="img/4.gif" alt="big grin">',
';;)'        =>  '<img src="img/5.gif" alt="batting eyelashes">',
'&gt;:D&lt;' =>  '<img src="img/6.gif" alt="big hug">',
':-/'        =>  '<img src="img/7.gif" alt="confused">',
':x'         =>  '<img src="img/8.gif" alt="love struck">',
':"&gt;'     =>  '<img src="img/9.gif" alt="blushing">',
':P'         =>  '<img src="img/10.gif" alt="tongue">',
':-*'        =>  '<img src="img/11.gif" alt="kiss">',
'=((' 		 =>  '<img src="img/12.gif" alt="broken heart">',
':-O'        =>  '<img src="img/13.gif" alt="surprise">',
'X('         =>  '<img src="img/14.gif" alt="angry">',
':&gt;'      =>  '<img src="img/15.gif" alt="smug">',
'B-)'        =>  '<img src="img/16.gif" alt="cool">',
':-S'        =>  '<img src="img/17.gif" alt="worried">',
'#:-S'       =>  '<img src="img/18.gif" alt="whew!">',
'&gt;:)'     =>  '<img src="img/19.gif" alt="devil">',
':(('        =>  '<img src="img/20.gif" alt="crying">',
':))'        =>  '<img src="img/21.gif" alt="laughing">',
':|'         =>  '<img src="img/22.gif" alt="straight face">',
'/:)'        =>  '<img src="img/23.gif" alt="raised eyebrows">',
'=))' 		 =>  '<img src="img/24.gif" alt="rolling on the floor">',
'O:-)'       =>  '<img src="img/25.gif" alt="angel">',
':-B'        =>  '<img src="img/26.gif" alt="nerd">',
'=;' 		 =>  '<img src="img/27.gif" alt="talk to the hand">',
':-c'        =>  '<img src="img/101.gif" alt="call me">',
':)]'        =>  '<img src="img/100.gif" alt="on the phone">',
'~X('        =>  '<img src="img/102.gif" alt="at wits\' end">',
':-h'        =>  '<img src="img/103.gif" alt="wave">',
':-t'        =>  '<img src="img/104.gif" alt="time out">',
'8-&gt;'     =>  '<img src="img/105.gif" alt="day dreaming">',
'I-)'        =>  '<img src="img/28.gif" alt="sleepy">',
'8-|'        =>  '<img src="img/29.gif" alt="rolling eyes">',
'L-)'        =>  '<img src="img/30.gif" alt="loser">',
':-&amp;'    =>  '<img src="img/31.gif" alt="sick">',
':-$'        =>  '<img src="img/32.gif" alt="don\'t tell anyone">',
'[-('        =>  '<img src="img/33.gif" alt="no talking">',
':O)'        =>  '<img src="img/34.gif" alt="clown">',
'8-}'        =>  '<img src="img/35.gif" alt="silly">',
'&lt;:-P'    =>  '<img src="img/36.gif" alt="party">',
'(:|'        =>  '<img src="img/37.gif" alt="yawn">',
'=P~' 		 =>  '<img src="img/38.gif" alt="drooling">',
':-?'        =>  '<img src="img/39.gif" alt="thinking">',
'#-o'        =>  '<img src="img/40.gif" alt="d\'oh">',
'=D&gt;' 	 =>  '<img src="img/41.gif" alt="applause">',
':-SS'       =>  '<img src="img/42.gif" alt="nail biting">',
'@-)'        =>  '<img src="img/43.gif" alt="hypnotized">',
':^o'        =>  '<img src="img/44.gif" alt="liar">',
':-w'        =>  '<img src="img/45.gif" alt="waiting">',
':-&lt;'     =>  '<img src="img/46.gif" alt="sigh">',
'&gt;:P'     =>  '<img src="img/47.gif" alt="phbbbbt">',
'&lt;):)'    =>  '<img src="img/48.gif" alt="cowboy">',
'X_X'        =>  '<img src="img/109.gif" alt="I don\'t want to see">',
':!!'        =>  '<img src="img/110.gif" alt="hurry up!">',
'\m/'        =>  '<img src="img/111.gif" alt="rock on!">',
':-q'        =>  '<img src="img/112.gif" alt="thumbs down">',
':-bd'       =>  '<img src="img/113.gif" alt="thumbs up">',
'^#(^'       =>  '<img src="img/114.gif" alt="it wasn\'t me">',
':ar!'       =>  '<img src="img/pirate_2.gif" alt="pirate*">'
];
 ?>